services:
  postgres-department:
    env_file: "pds-compose.env"
    image: postgres:17.2-bookworm
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=citizix_db

  pgadmin:
    image: dpage/pgadmin4:latest