server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://172.17.0.1:5432
    username: pguser
    password: pgpass
    name: department_db

#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG